[initializers.gameConstants]
CAN_SPAWN = true
# Player Init
INITIAL_GOLD = 4000
INITIAL_SOULS = 32
# Mana
MAX_MANA = 10000
NUMBER_OF_SECONDS_FOR_ONE_MANA_REGEN = 1
MANA_PER_ACTION_TYPE = [
  # Mine
  1, 
  # Claim
  10, 
  # Upgrade
  100
]
# Mining
GOLD_PER_GOLD_BLOCK = 20
SOULS_PER_SOUL_BLOCK = 2
SOUL_PERLIN_THRESHOLD = 42
SOUL_GROUND_RESOURCE_PERLIN_THRESHOLD = 44
GOLD_PERLIN_THRESHOLD = 41
# Bank
DRIP_AMOUNT = "250000000000000000"
TIME_BETWEEN_DRIPS = 100
# Upgrades
WALL_PRICE = 20
TILE_UPGRADE_PRICES = [0, 0, 40, 10, 100, 50, 20]
INFLUENCE_PER_TILE_UPGRADE = [1, 32, 1, 1, 1, 1, 1]
# Dungeon Heart, Gold Storage, Soul Storage
TILE_UPGRADE_GOLD_STORAGE = [1000, 250, 0]
TILE_UPGRADE_SOUL_STORAGE = [8, 0, 4]
POPULATION_PER_LAIR = 1
# Harvest
HARVEST_BOOST_TRANCHES = [25, 75, 100, 50]
TILE_UPGRADE_NUMBER_OF_SECONDS_FOR_ONE_HARVEST = [0, 0, 3, 0, 4, 0, 10]
TILE_UPGRADE_MAX_HARVEST = [0, 0, 100, 0, 100, 0, 100]
MAX_SOULS_HARVESTED_PER_SOUL_TILE = 10
MAX_GROUND_BYTE_VALUE_TO_BE_SOUL_TILE = 16
# Delayed actions
# TileDelayedActionType -> bool -> uint256
DELAYED_ACTIONS_MIN_SECOND_DELAY = [
  # WALL
  [10, 0],
  # UNWALL
  [2, 30],
  # FORCE_MINE
  [2, 20],
]
SECONDS_UNTIL_EXPIRED_DELAYED_ACTION = 256
# Influence
MIN_INFLUENCE_FOR_CONTROL = 8
# Creatures
CREATURES_MIN_SECOND_DELAY_BETWEEN_SPAWN = 5
CREATURES_UNIQUE_STAT_MULTIPLIER = 5
CREATURES_UNIQUE_GROUP_NEG_BOOST = -50
# CreatureSpecies -> CreatureType -> (gold, souls)
CREATURES_PRICE = [[[20, 1], [30, 2], [30, 2], [30, 2], [40, 3]]]
# CreatureSpecies -> ATK/LIFE -> value
CREATURES_BASE_STAT_PER_SPECIES = [[20, 100]]
# CreaturesType -> CreaturesType -> value;
CREATURES_TYPE_STRENGTH_AGAINST_TYPE = [
  [
    0,
    0,
    0,
    0,
    100,
  ],
  [
    20,
    0,
    40,
    0,
    0,
  ],
  [
    20,
    0,
    0,
    40,
    0,
  ],
  [
    20,
    40,
    0,
    0,
    0,
  ],
  [
    0,
    0,
    0,
    0,
    0,
  ],
]
# CreatureSpecies -> 0-3 -> value
CREATURES_INFLUENCE_PER_SPECIES_AND_LEVEL = [[35, 50, 65, 80]]
CREATURES_GROUP_MULTIPLIERS = [0, 10, 20, 30, 40]
CREATURES_MAX_NUMBER_OF_ROUNDS_PER_COMBAT = 30
CREATURES_MAX_REGION_DISTANCE_FOR_MOVE = 2
PERLIN_1_KEY = 42
PERLIN_2_KEY = 43
PERLIN_1_SCALE = 1
PERLIN_2_SCALE = 1
[initializers]
numberOfRegionsPerSide = 64
